apiVersion: v1
kind: Service
metadata:
  name: cas-k
spec:
  ports:
  - name: cas-k
    port: 9042
    targetPort: 9042
    protocol: TCP
  selector:
    app: cas-k
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cas-k
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cas-k
    spec:
      containers:
        - name: cas-k
          image: cassandra:2.2
          ports:
            - containerPort: 9042
