---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin-cas
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: kong-admin-cas
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: kong-proxy-cas
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: kong-cas

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-rc-cas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong-rc-cas
        app: kong-cas
    spec:
      containers:
      - name: kong-cas
        image: kong
        env:
          - name: KONG_DATABASE
            value: cassandra
          - name: KONG_CASSANDRA_CONTACT_POINTS 
            value: 192.168.3.2
        ports:
        - name: admin-cas
          containerPort: 8001
          protocol: TCP
        - name: proxy-cas
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl-cas
          containerPort: 8443
          protocol: TCP
        - name: surf-tcp-cas
          containerPort: 7946
          protocol: TCP
        - name: surf-udp-cas
          containerPort: 7946
          protocol: UDP
