apiVersion: v1
kind: Service
metadata:
  name: kong-pgl
spec:
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: kong-pgl
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kong-pgl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kong-pgl
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
            - name: POSTGRES_DB
              value: kong
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
